[package]
    edition = "2021"
    name    = "aoc2024"
    version = "0.1.0"

[dependencies]
    ansi_term = "0.12"
    clap      = { version = "4", features = ["derive"] }
    itertools = "0.13"
    paste     = "1"
    regex     = "1"
    thiserror = "2"
